name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: heistline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy via SFTP to IONOS
        uses: pressidium/lftp-deploy@v1.0.0
        with:
          host: ${{ secrets.IONOS_FTP_SERVER }}
          port: 22
          username: ${{ secrets.IONOS_FTP_USERNAME }}
          password: ${{ secrets.IONOS_FTP_PASSWORD }}
          localDir: heistline/dist/
          remoteDir: /htdocs/
          sftp: true
