name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: heistline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: SFTP Deploy to IONOS
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{ secrets.IONOS_SFTP_PRIVATE_KEY }}
          remote-user: ${{ secrets.IONOS_FTP_USERNAME }}
          server-ip: ${{ secrets.IONOS_FTP_SERVER }}
          remote-path: /htdocs/
          local-path: heistline/dist/
