name: Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        working-directory: heistline
        run: |
          npm install
          npm run build

      - name: Upload files to IONOS via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IONOS_FTP_SERVER }}
          username: ${{ secrets.IONOS_FTP_USERNAME }}
          password: ${{ secrets.IONOS_FTP_PASSWORD }}
          port: 22
          source: "dist/*"          
          target: "htdocs"
